version: 'latest'
services:
  postgres:
    image: 'postgres'
    container_name: postgres
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal-network
      
  backend:
    build: ./backend
    env_file: 
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - internal-network
      - internet
    ports:
      - '4000:3000'

  frontend:
    build: ./frontend
    image: frontend
    networks:
      - internet
    ports:
      - '8081:80'

volumes:
  postgres-data:

networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge

